-- config.ld
file = {
'scriptutils.lua',
'scriptextender.lua',
'..\\baked\\mod\\_api.lua',
'..\\baked\\mod\\_api_replaceondeath.lua',
'..\\baked\\mod\\_funcarray.lua',
'..\\baked\\mod\\_statemachine.lua',
'..\\baked\\mod\\_gameobject.lua',
'..\\baked\\mod\\_hook.lua',
'..\\baked\\mod\\_printfix.lua',
'..\\baked\\mod\\_requirefix.lua',
'..\\baked\\mod\\_mapdata.lua',
'..\\baked\\mod\\_table_show.lua'
}